### ISSUE TITLE
Canceling a running future

### ISSUE THREAD

**Issue by romansvozil** [awestlake87/pyo3-asyncio#47]
Hi, I'm playing around with PyO3, and I'm trying to implement some scripting API for my game (let's say walking & attacking), but the issue is that sometimes I would like to cancel the already running future.

Code:
```py3
from asyncio import wait_for   
from asyncio import TimeoutError

import chrono_api

class ChronoScript: 
    async def run(self) -> None:
        try:
            await wait_for(chrono_api.walk(5), 2.)
        except TimeoutError:
            print("Walking was canceled!")
```

Where the walk function looks like this:
```rs
#[pyfunction]
fn walk(py: Python, duration: i32) -> PyResult<&PyAny> {
    pyo3_asyncio::tokio::future_into_py(py, async move {
        for i in 0..duration {
            println!("Walking tick: {}", i);
            tokio::time::sleep(std::time::Duration::from_secs(1)).await;
        }
        Ok(Python::with_gil(|py| py.None()))
    })
}
```

Real output
```
Walking tick: 0
Walking tick: 1
Walking tick: 2
Walking was canceled!
Walking tick: 3
Walking tick: 4
Walking tick: 5
```

The expected output 
```
Walking tick: 0
Walking tick: 1
Walking tick: 2 (maybe)
Walking was canceled!
-- nothing more --
```

Is it possible to somehow achieve this output? 
I'm sorry if I missed something 👍 

(Whole repo can be found here: https://github.com/romansvozil/embedded-python/tree/master/src)

**Comment by awestlake87** [comment]
What versions of Python and pyo3-asyncio are you using? I know recently we put in a patch that should make cancellation work.

I just plugged your code into a test project and it gave the expected output for me:

```toml
# Cargo.toml

[package]
name = "pyo3-asyncio-lib"
version = "0.1.0"
authors = ["Andrew J Westlake <awestlake87@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "my_async_module"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.14", features = ["extension-module"] }
pyo3-asyncio = { version = "0.14", features = ["tokio-runtime"] }
tokio = "1.4"
```

```rust
//! lib.rs

use pyo3::{prelude::*, wrap_pyfunction};

#[pyfunction]
fn walk(py: Python, duration: i32) -> PyResult<&PyAny> {
    pyo3_asyncio::tokio::future_into_py(py, async move {
        for i in 0..duration {
            println!("Walking tick: {}", i);
            tokio::time::sleep(std::time::Duration::from_secs(1)).await;
        }
        Ok(Python::with_gil(|py| py.None()))
    })
}
#[pymodule]
fn my_async_module(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(walk, m)?)?;

    Ok(())
}
```

```py
# example.py
import asyncio
from asyncio import wait_for   
from asyncio import TimeoutError

import my_async_module as chrono_api

class ChronoScript: 
    async def run(self) -> None:
        try:
            await wait_for(chrono_api.walk(5), 2.)
        except TimeoutError:
            print("Walking was canceled!")

asyncio.run(ChronoScript().run())
```

```bash
maturin develop && python3 example.py
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at python3
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
Walking tick: 0
Walking tick: 1
Walking tick: 2
Walking was canceled!
```

Occasionally the order of `Walking tick: 2` and `Walking was canceled!` are switched, but I don't see it going up to 4.
